# Generated by Django 5.1.2 on 2024-10-19 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_customuser_user_type_inventoryorders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodPrice', models.FloatField()),
                ('qty', models.IntegerField()),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodid', to='inventory.item')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_on', models.DateTimeField(auto_now_add=True)),
                ('net_total', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('payment_status', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressid', to='inventory.address')),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartid', to='onlinestore.cart')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
