# Generated by Django 5.1.2 on 2024-11-22 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventoryorders_qty_received'),
        ('onlinestore', '0002_order_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prodId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prodPrice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='placed_on',
        ),
        migrations.AddField(
            model_name='cart',
            name='placed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodPrice', models.FloatField()),
                ('qty', models.IntegerField()),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartinfo', to='onlinestore.cart')),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodid', to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
