# Generated by Django 5.1.2 on 2024-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0003_remove_cart_prodid_remove_cart_prodprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_receipt',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
