# Generated by Django 5.1.2 on 2024-11-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0004_remove_order_payment_receipt_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='prodPrice',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
