# Generated by Django 5.1.2 on 2024-10-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('sales', 'sales emp'), ('warehouse', 'warehouse emp'), ('rider', 'rider')], max_length=12),
        ),
        migrations.CreateModel(
            name='InventoryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('qty_ordered', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemid', to='inventory.item')),
                ('vendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorId', to='inventory.vendor')),
            ],
        ),
    ]
