# Generated by Django 5.1.2 on 2024-10-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_customuser_user_type_inventoryorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='med_formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medFormula', to='inventory.medformula'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_strip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty_per_pack',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
