# Generated by Django 5.1.2 on 2024-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_company_item_description_item_dosage_strength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_per_strip',
            new_name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='packaging_unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
