# Generated by Django 5.1.2 on 2024-10-22 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_per_strip_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medformula',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_name', to='inventory.medcategory'),
        ),
    ]
