# Generated by Django 5.1.2 on 2024-10-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_medimage_itemid_medimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
