# Generated by Django 5.1.2 on 2024-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_item_qty_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_qty',
            field=models.IntegerField(default=0),
        ),
    ]
