# Generated by Django 5.1.2 on 2024-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_current_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
