# Generated by Django 5.1.2 on 2024-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_ordered',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
