# Generated by Django 5.1.2 on 2024-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorders',
            name='qty_ordered',
            field=models.CharField(max_length=50),
        ),
    ]
