# Generated by Django 5.1.2 on 2024-11-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryorders_qty_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorders',
            name='qty_received',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
