# Generated by Django 5.1.2 on 2024-11-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
